# ISO 17025 Verification
# The aim of this workflow is to coninually test and assess the repository
# against reference material where possible
name: 17025 Validation
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  schedule:
    #run every Monday at 0200 AEST/0100 AEDST or on update to repository
    - cron:  '0 15 * * 1'

jobs:
  install-jadx:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout JadX
      uses: actions/checkout@v4
    - name: Install JadX
      run: ./gradlew dist
    - name: Test 1 - Decompile reference material APK
      run: |
            mkdir out
            jadx "refmat/Cellcrypt Enterprise_4.72.4_Apkpure.apk" -d out
      #TODO: add a test to make sure decompile worked. Maybe perform a search
      #      per the CC for certain parameters?
      
